### ISSUE TITLE
List config example fails with segfault

### ISSUE THREAD

**Issue by Sija** [zaeleus/ffi-gphoto2#12]
More details in [this gist](https://gist.github.com/Sija/a1cf6e63393fea4dc54b97f6a5a76ae8).

**Comment by Sija** [comment]
Forgot to add that I'm using Canon 40D + gphoto2 with following specs:
```
gphoto2         2.5.10         clang, popt(m), no exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.10         all camlibs, clang, ltdl, no EXIF
libgphoto2_port 0.12.0         clang, ltdl, USB, serial without locking
```

**Comment by zaeleus** [comment]
Does the previous example without labels work?

https://github.com/zaeleus/ffi-gphoto2/blob/aa3581367656e5efa7adf0b542bcf4ea6e021fd1/examples/list_config.rb

**Comment by Sija** [comment]
@zaeleus yap, runs smoothly as nothing happened.

**Comment by zaeleus** [comment]
And single widget labels work for you, e.g., `camera[:syncdatetime].label`, `camera[:iso].label`, etc?

Can you confirm that `gphoto2 --list-all-config` works?

**Comment by Sija** [comment]
- `camera[:iso].label` crashes with the same error
- `gphoto2 --list-all-config` does work

**Comment by zaeleus** [comment]
Did #10 ever work when you submitted it? I can't reproduce the issue on multiple machines with different devices.

**Comment by Sija** [comment]
I didn't try TBH

**Comment by zaeleus** [comment]
Looking at the paths and line numbers in your backtrace, you're running the 0.5.1 release, where indeed `CameraWidget#label` does not work. This was touched in 7ed0923 and fixed with ed46aeb. The most recent `list_config.rb` example currently only works with anything >= ed46aeb.

**Comment by Sija** [comment]
Good point, it's probably bc of `require 'gphoto2'` which loads lib installed through _rubygems_ instead of from `../lib/`. Maybe it would be worth changing require path for all the examples to `../lib/gphoto2`?

**Comment by zaeleus** [comment]
If you want to run files in the context of the project, use [`bundle exec`](http://bundler.io/man/bundle-exec.1.html), e.g, `bundle exec ruby examples/list_config.rb`.

**Comment by Sija** [comment]
Works as expected, thx!
