### ISSUE TITLE
ffi-gphoto2 gem not working when bundled and used in Sinatra/Rails app

### ISSUE THREAD

**Issue by tory** [zaeleus/ffi-gphoto2#2]
Great gem! I can only seem to use it in one off ruby scripts though. When I include it in a Gemfile for a Rails or Sinatra app, bundle install and require 'gphoto2' I am met with the following error:

.rvm/gems/ruby-2.1.2/gems/ffi-gphoto2-0.5.0/lib/ffi/gphoto2_port.rb:3:in `module:GPhoto2Port': uninitialized constant FFI::Library (NameError)

Any thoughts?

**Comment by ameuret** [comment]
For the record it is now 2017 and launching `bundle console` blows up with the same message until 'ffi' is explicitly stated above 'ffi-gphoto2' in the Gemfile as @tory said.
(ruby 2.3.3p222)

**Comment by zaeleus** [comment]
@ameuret, I didn't know this was still an issue. I pushed a fix in 0.7.1.
